# Generated by Django 4.0.3 on 2022-05-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_state_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='State',
            new_name='state',
        ),
    ]
