# Generated by Django 4.0.3 on 2022-05-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_state_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='State',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
