# Generated by Django 4.0.3 on 2022-05-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='State',
        ),
    ]
