# Generated by Django 4.0.3 on 2022-05-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True),
        ),
    ]
