# Generated by Django 4.0.3 on 2022-05-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
