# Generated by Django 4.0.3 on 2022-05-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
