# Generated by Django 4.0.3 on 2022-05-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
