# Generated by Django 4.0.3 on 2022-05-22 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('Appartement', 'appartement'), ('House', 'house'), ('Industrial', 'industrial'), ('Commercial', 'commercial'), ('Land', 'Land')], default='Appartement', max_length=11)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=9, unique=True)),
                ('whatfor', models.CharField(choices=[('for_rent', 'for rent'), ('for_sale', 'for sale')], default='for_rent', max_length=8)),
                ('size', models.DecimalField(decimal_places=0, max_digits=6, null=True)),
                ('rooms', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('Location', models.CharField(blank=True, max_length=255)),
                ('Lat', models.DecimalField(decimal_places=20, max_digits=25)),
                ('Long', models.DecimalField(decimal_places=20, max_digits=25)),
                ('image', models.ImageField(upload_to='API/images')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='API.product')),
            ],
        ),
    ]
