# Generated by Django 4.0.3 on 2022-05-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_product_image_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.FileField(null=True, upload_to='API/images'),
        ),
    ]
