# Generated by Django 4.0.3 on 2022-04-24 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Costumer',
        ),
    ]
