# Generated by Django 4.0.3 on 2022-04-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_delete_costumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True),
        ),
    ]
