# Generated by Django 4.0.3 on 2022-05-22 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='owner',
            new_name='bookmarked_by',
        ),
    ]
