# Generated by Django 4.0.3 on 2022-05-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_rename_owner_bookmark_bookmarked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(null=True, upload_to='API/images'),
        ),
    ]
