# Generated by Django 4.0.3 on 2022-04-26 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='likedposts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.DecimalField(decimal_places=0, max_digits=9)),
                ('likedpostsid', models.DecimalField(decimal_places=0, max_digits=9)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedposts', to='API.product')),
            ],
        ),
    ]
