# Generated by Django 4.0.3 on 2022-05-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_likedposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='whatfor',
            field=models.CharField(choices=[('for_rent', 'for rent'), ('for_sale', 'for sale')], default='for_rent', max_length=8),
        ),
    ]
