# Generated by Django 4.0.3 on 2022-05-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_productimages_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.FileField(upload_to='API/images'),
        ),
    ]
