# Generated by Django 4.0.3 on 2022-05-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_product_whatfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('APP', 'appartement'), ('HO', 'house'), ('IN', 'industrial'), ('CO', 'commercial'), ('LA', 'Land')], default='APP', max_length=3),
        ),
    ]
