# Generated by Django 4.0.3 on 2022-05-24 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_product_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pic',
        ),
    ]
