# Generated by Django 4.0.3 on 2022-05-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rooms',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
    ]
