# Generated by Django 4.0.3 on 2022-05-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_remove_product_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.FileField(null=True, upload_to='API/images'),
        ),
    ]
