# Generated by Django 4.0.3 on 2022-05-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_product_rooms_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
