# Generated by Django 4.0.3 on 2022-05-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('Appartement', 'appartement'), ('House', 'house'), ('Industrial', 'industrial'), ('Commercial', 'commercial'), ('Land', 'Land')], default='Appartement', max_length=11),
        ),
    ]
