# Generated by Django 4.0.3 on 2022-05-24 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0014_alter_productimages_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='bookmarked_by',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
