# Generated by Django 4.0.3 on 2022-05-17 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_alter_product_owner_alter_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
