# Generated by Django 4.0.3 on 2022-05-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Lat',
            field=models.DecimalField(decimal_places=20, default=1, max_digits=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='Long',
            field=models.DecimalField(decimal_places=20, default=1, max_digits=25),
            preserve_default=False,
        ),
    ]
