# Generated by Django 4.0.3 on 2022-06-02 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0016_remove_bookmark_owner_bookmark_bookmarked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('Appartement', 'appartement'), ('House', 'house'), ('Industrial', 'industrial'), ('Commercial', 'commercial'), ('Land', 'Land')], default='Appartement', max_length=11)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=9, unique=True)),
                ('whatfor', models.CharField(choices=[('for_rent', 'for rent'), ('for_sale', 'for sale')], default='for_rent', max_length=8)),
                ('size', models.DecimalField(decimal_places=0, max_digits=6, null=True)),
                ('rooms', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('Location', models.CharField(blank=True, max_length=255)),
                ('Lat', models.DecimalField(decimal_places=20, max_digits=25)),
                ('Long', models.DecimalField(decimal_places=20, max_digits=25)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='OfferImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(null=True, upload_to='API/images')),
                ('Offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='API.offer')),
            ],
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='product',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='Offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to='API.offer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='Offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='API.offer'),
            preserve_default=False,
        ),
    ]
