# Generated by Django 4.0.3 on 2022-05-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_remove_review_name_review_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='API/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='rooms',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
        migrations.DeleteModel(
            name='likedposts',
        ),
    ]
