# Generated by Django 4.0.3 on 2022-05-20 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_remove_review_name_review_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='likedposts',
        ),
    ]
