# Generated by Django 4.0.3 on 2022-05-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_alter_product_rooms_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='API/images'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
